token: "lip_iR7FzNuyAhocXfWVKUYm"         # Lichess OAuth2 Token.

engine:                                   # Engine settings.
  dir: "./engines"               # Directory containing the engine.
  name: "fsf_linux"        # Binary name of the engine to use.
  ponder: true                            # Think on opponent's time.
  polyglot:
    enabled: true                         # Activate polyglot book.
    books:
      white: "lichess-book"                      # Name of the book to use as white.
      black: "lichess-book"                         # Name of the book to use as black.
      standard: null            # Name of the book to use if there is no specific book for white, black or chess960.
      chess960: null                      # Name of the book to use for Chess960.
    selection: "best_move"                # Move selection is one of "weighted_random", "uniform_random" or "best_move".
  pybook:
    enabled: false                        # Activate pybook.
    book: "/path/to/pybook"               # Path to pybook.
  online_moves:
    chessdb:
      enabled: false                      # Activate online moves from https://chessdb.cn/queryc_en/
      min_depth: 20                       # Minimum evaluation depth.
      min_time: 40                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
    lichess_cloud:
      enabled: false                       # Activate online moves from Lichess cloud eval.
      min_depth: 20                       # Minimum evaluation depth.
      min_time: 40                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
    online_egtb:
      enabled: false                      # Activate online endgame tablebases from Lichess.
      min_time: 10                       # Time the bot must have at least to use the online move.
      timeout: 3                          # Time the server has to respond.
  offer_draw:
    enabled: true                         # Activate whether the bot should offer draw.
    score: 5                              # If the absolute value of the score is less than or equal to this value, the bot offers/accepts draw (in cp)
    consecutive_moves: 10                 # How many moves in a row the absolute value of the score has to be below the draw value
    min_game_length: 50                   # Earliest move in which draw is offered.
  resign:
    enabled: false                        # Activate whether the bot should resign games.
    score: -1000                          # If the score is less than or equal to this value, the bot resigns (in cp).
    consecutive_moves: 5                  # How many moves in a row the score has to be below the resign value.
  uci_options:                            # Arbitrary UCI options passed to the engine. (Commenting allowed)
    Move Overhead: 400                    # Increase if your bot flags games too often.
    Threads: 3                            # Max CPU threads the engine can use.
    Hash: 134                             # Max memory (in megabytes) the engine can allocate.
    MultiPV: 70
    Skill Level: 20
    UCI_Elo : 2850
    Slow Mover: 40
    
    
move_overhead_multiplier: 3.0             # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.

challenge:                                # Incoming challenges. (Commenting allowed)
  concurrency: 1                          # Number of games to play simultaneously.
  min_increment: 0                        # Minimum amount of increment to accept a challenge.
  max_increment: 180                      # Maximum amount of increment to accept a challenge.
  min_initial: 0                          # Minimum amount of initial time to accept a challenge.
  max_initial: 1000                        # Maximum amount of initial time to accept a challenge.
  variants:                               # Chess variants to accept (https://lichess.org/variant).
    - standard
    - chess960
#   - fromPosition
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:                          # Time controls to accept.
    - bullet
    - blitz
    - rapid
    - classical
  bot_modes:                              # Game modes to accept against BOTs.
    - casual                              # Unrated games.
    - rated                               # Rated games
  human_modes:                            # Game modes to accept against humans.
    - casual                              # Unrated games.
    - rated                               # Rated games. 

matchmaking:
  initial_time: 30                        # Initial time for matchmaking mode.
  increment: 0                            # Increment time for matchmaking mode.
  rated: true                             # Activate rated games in matchmaking mode.
  timeout: 10                             # Time until a challenge is canceled. 
# min_rating_diff: 0                      # Minimum rating distance to opponent. (Commenting allowed)
# max_rating_diff: 300                    # Maximum rating distance to opponent. (Commenting allowed)


books: 
    lichess-book: "./engines/lichess-book.bin"  # Name of the opening book (to be used above in the polyglot section) and path to the polyglot opening book.  
